# web ????
server:
  port: 9188
  shutdown: GRACEFUL
  servlet:
    context-path: /${spring.application.name}

# spring ??
spring:
  application:
    name: at-bot
  datasource:
    url: jdbc:mysql://209.182.237.103:3306/at_bot?autoReconnect=true&failOverReadOnly=false
    username: atbot
    password: atBot@520
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 20
      max-active: 50
      max-wait: 2000
      min-idle: 10
      validation-query: select 1
  data:
    redis:
      # 地址
      host: 209.182.237.103
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password: atBot@520
      # 连接超时时间
      timeout: 5000
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1

mybatis-plus:
  mapper-locations: classpath*:com/bottrade/bot/dao/mapper/**/*.xml

# rocket mq配置
rocketmq:
  name-server: 209.182.237.103:9876
  producer:
    group: at-bot
    send-message-timeout: 300000

ai-ocr:
  online-url: http://127.0.0.1:6006/online-ocr
  file-url: http://127.0.0.1:6006/file-ocr